# Importações

In [1]:
import pandas as pd

# Carregando os dados

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
data = pd.read_csv(url, sep=',')
data.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [6]:
# acrescentando nome as colunas
data.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
data.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

# Tratamento e Análise

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [69]:
data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [70]:
# quais e quantos valores existem em cada coluna
for column in data.columns:
    print(data[column].value_counts())
    print()

buying
0    432
2    432
1    432
3    431
Name: count, dtype: int64

maint
0    432
2    432
1    432
3    431
Name: count, dtype: int64

doors
1    432
2    432
3    432
0    431
Name: count, dtype: int64

persons
1    576
2    576
0    575
Name: count, dtype: int64

lug_boot
1    576
0    576
2    575
Name: count, dtype: int64

safety
2    576
0    576
1    575
Name: count, dtype: int64

class
2    1209
0     384
1      69
3      65
Name: count, dtype: int64

In [10]:
# label encoding para transformar variáveis categoricas em numericas (prefericalmente com categoricas ordinais)
from sklearn.preprocessing import LabelEncoder

In [11]:
# objeto encoding
le = LabelEncoder()

In [12]:
# percorrendo coluna por coluna e transformando
for col in data.columns:
    data[col] = le.fit_transform(data[col])

In [13]:
data.head()

   buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       2      2
1       3      3      0        0         2       0      2
2       3      3      0        0         1       1      2
3       3      3      0        0         1       2      2
4       3      3      0        0         1       0      2

# Separação dos dados

In [15]:
# target (o que o modelo vai tentar prever)
y = data['class']

In [27]:
# features (o que o modelo usa pra aprender)
X = data.drop('class', axis=1)

In [19]:
# separar parte que é treino (80%) e parte que é teste (20%)
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1381, 6)
(346, 6)
(1381,)
(346,)

# Treinamento

### Regressão Logística

In [30]:
# regressao logistica
from sklearn.linear_model import LogisticRegression

In [31]:
# criar modelo
model = LogisticRegression()

In [32]:
# treinar
model.fit(X_train, y_train)

LogisticRegression()

In [33]:
# previsoes
y_pred = model.predict(X_test)

In [34]:
# avaliacao
from sklearn.metrics import accuracy_score

In [35]:
# acuracia
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.684971098265896

In [36]:
# relatorio
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.32      0.16      0.21        77
           1       0.00      0.00      0.00        15
           2       0.73      0.95      0.83       237
           3       0.50      0.06      0.11        17

    accuracy                           0.68       346
   macro avg       0.39      0.29      0.28       346
weighted avg       0.60      0.68      0.62       346

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

### Random Forest

In [39]:
# random forest pra classificacao
from sklearn.ensemble import RandomForestClassifier

In [38]:
# criar
rf = RandomForestClassifier(random_state=42)

In [40]:
# treinar
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [42]:
# prever
y_pred_rf = rf.predict(X_test)

In [43]:
# avaliar
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

0.9624277456647399
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        77
           1       0.91      0.67      0.77        15
           2       0.99      1.00      0.99       237
           3       0.79      0.88      0.83        17

    accuracy                           0.96       346
   macro avg       0.91      0.87      0.88       346
weighted avg       0.96      0.96      0.96       346

### Balanceando dados e retreinando com Random Forest

#### Oversampling

In [44]:
# balanceamento basico com imblearn
from imblearn.over_sampling import RandomOverSampler

In [45]:
# criar o sampler
ros = RandomOverSampler(random_state=42)

In [46]:
# aplicar so nos dados de treino!!
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)

In [49]:
# treinar novamente
rf.fit(X_train_res, y_train_res)
y_pred_rf = rf.predict(X_test)

In [50]:
# avaliar novamente
print(accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

0.9710982658959537
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        77
           1       0.91      0.67      0.77        15
           2       1.00      1.00      1.00       237
           3       0.88      0.88      0.88        17

    accuracy                           0.97       346
   macro avg       0.93      0.88      0.90       346
weighted avg       0.97      0.97      0.97       346

#### SMOTE

In [51]:
# balanceando com SMOTE
from imblearn.over_sampling import SMOTE

In [52]:
# criar
smote = SMOTE(random_state=42)

In [53]:
# aplicar nos dados de treino
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [54]:
# treinar de novo
rf.fit(X_train_smote, y_train_smote)
y_pred_smote = rf.predict(X_test)

In [55]:
# avaliar de novo
print(accuracy_score(y_test, y_pred_smote))
print(classification_report(y_test, y_pred_smote))

0.9682080924855492
              precision    recall  f1-score   support

           0       0.94      0.97      0.96        77
           1       0.90      0.60      0.72        15
           2       1.00      1.00      1.00       237
           3       0.75      0.88      0.81        17

    accuracy                           0.97       346
   macro avg       0.90      0.86      0.87       346
weighted avg       0.97      0.97      0.97       346

### XGBoost

In [56]:
# instalando no colab
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [57]:
# importando para classificacao
from xgboost import XGBClassifier

In [58]:
# criar modelo
xgb = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

In [59]:
# treinar
xgb.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [01:35:18] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [60]:
# prever
y_pred_xgb = xgb.predict(X_test)

In [62]:
# avaliar

print(accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

0.9855491329479769
              precision    recall  f1-score   support

           0       0.99      0.99      0.99        77
           1       1.00      0.80      0.89        15
           2       1.00      1.00      1.00       237
           3       0.80      0.94      0.86        17

    accuracy                           0.99       346
   macro avg       0.95      0.93      0.94       346
weighted avg       0.99      0.99      0.99       346

### SVM

In [63]:
# importar
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [64]:
# escalando/padronizando os dados
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [65]:
# criar modelo
svm = SVC(random_state=42)

In [66]:
# treinar
svm.fit(X_train_scaled, y_train)

SVC(random_state=42)

In [67]:
# prever
y_pred_svm = svm.predict(X_test_scaled)

In [68]:
# avaliar
print(accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

0.8872832369942196
              precision    recall  f1-score   support

           0       0.70      0.90      0.78        77
           1       0.00      0.00      0.00        15
           2       0.97      0.95      0.96       237
           3       0.93      0.82      0.88        17

    accuracy                           0.89       346
   macro avg       0.65      0.67      0.65       346
weighted avg       0.86      0.89      0.87       346

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))